---
- name: Setup Docker and Run Scripts on Ubuntu Server
  hosts: web
  become: yes
  gather_facts: yes
  tasks:
    - name: Update APT package manager repositories
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker's stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x,o+x'

    - name: Set safe.directory
      become: yes
    #  become_user: ansible
      shell: git config --global --add safe.directory /home/ansible/Airflow_deployment 
      args:
         warn: no    

    - name:
      git:
        repo: git@github.com:Sorrentum-Groups/Airflow_deployment.git
        dest: /home/ansible/Airflow_deployment 
        clone: yes
        update: yes

    - name: Execute a script
      shell: sh /home/ansible/Airflow_deployment/sorrentum_ansible/ansible.sh

    - name: Update apt package database
      apt:
        update_cache: yes

    - name: Install unzip is needed to install AWScli
      apt:
        name: unzip
        state: present

    - name: Download AWS CLI
      get_url:
        url: https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Run AWS CLI installer
      command: sudo /tmp/aws/install    

    - name: Check if SES SMTP user exists
      command: aws iam get-user --user-name ses-smtp-user.airflow_prod
      register: user
      ignore_errors: True

    - name: Show user
      debug:
        var: user

    - name: Create user if it does not exist
      command: aws iam create-user --user-name ses-smtp-user.airflow_prod
      when: user is failed 
